# -*- coding: utf-8 -*-
"""Autitos2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rFASsNO5TMAI1-IvT8vY81dK1GzxpQd
"""

import pandas as pd

data = {
    "Escenario": ["Situación Actual", "Alternativa 1", "Alternativa 2"],
    "Vel_Buses_kmh": [12.5, 12.5, 21.0],
    "Tiempo_Buses_min": [9.6, 9.6, 5.7],
    "Vel_Autos_kmh": [16.0, 16.5, 14.5],
    "Demora_Friccion_seg": [120.0, 110.0, 25.0],
    "Var_TP": [0.15, 0.30, 0.90],
    "Var_Peatonal": [0.35, 0.85, 0.85],
    "Var_Logistica": [0.40, 0.40, 0.90],
    "Var_Flujo": [0.25, 0.40, 0.70],
    "Peso_TP": [0.40, 0.35, 0.45],
    "Peso_Peatonal": [0.35, 0.40, 0.35],
    "Peso_Logistica": [0.15, 0.15, 0.15],
    "Peso_Flujo": [0.10, 0.10, 0.05]
}

df = pd.DataFrame(data)

df["ICV_Calculado"] = (
    (df["Var_TP"] * df["Peso_TP"]) +
    (df["Var_Peatonal"] * df["Peso_Peatonal"]) +
    (df["Var_Logistica"] * df["Peso_Logistica"]) +
    (df["Var_Flujo"] * df["Peso_Flujo"])
)

def clasificar_estado(icv):
    if icv > 0.70:
        return "Óptimo"
    elif 0.41 <= icv <= 0.70:
        return "Saturado"
    else:
        return "Crítico"

df["Estado_Vial"] = df["ICV_Calculado"].apply(clasificar_estado)

columnas_reporte = [
    "Escenario",
    "ICV_Calculado",
    "Estado_Vial",
    "Vel_Buses_kmh",
    "Tiempo_Buses_min",
    "Vel_Autos_kmh",
    "Demora_Friccion_seg"
]

df_reporte = df[columnas_reporte]

print("=" * 105)
print(" COMPARATIVA DE ESCENARIOS VIALES: EVALUACIÓN MULTICRITERIO (PESOS DINÁMICOS)")
print("=" * 105)
print(df_reporte.to_string(index=False, float_format="{:.2f}".format))
print("=" * 105)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

tramos = [
    "T1 (F. Lazcano)",
    "T2 (Bloqueos)",
    "T3 (Intermedio A)",
    "T4 (Intermedio B)",
    "T5 (Curiñanca)"
]
escenarios = ["1. Base", "2. Alternativa 1", "3. Alternativa 2"]

data = [
    [tramos[0], escenarios[0], 0.85, 0.70, 0.60, 0.50],
    [tramos[0], escenarios[1], 0.85, 0.85, 0.60, 0.50],
    [tramos[0], escenarios[2], 0.90, 0.85, 0.60, 0.50],
    [tramos[1], escenarios[0], 0.15, 0.35, 0.40, 0.25],
    [tramos[1], escenarios[1], 0.30, 0.85, 0.40, 0.40],
    [tramos[1], escenarios[2], 0.90, 0.85, 0.90, 0.70],
    [tramos[2], escenarios[0], 0.65, 0.60, 0.55, 0.60],
    [tramos[2], escenarios[1], 0.70, 0.85, 0.55, 0.65],
    [tramos[2], escenarios[2], 0.85, 0.85, 0.70, 0.75],
    [tramos[3], escenarios[0], 0.80, 0.75, 0.65, 0.70],
    [tramos[3], escenarios[1], 0.80, 0.85, 0.65, 0.70],
    [tramos[3], escenarios[2], 0.85, 0.85, 0.70, 0.75],
    [tramos[4], escenarios[0], 0.90, 0.85, 0.70, 0.80],
    [tramos[4], escenarios[1], 0.90, 0.90, 0.70, 0.80],
    [tramos[4], escenarios[2], 0.95, 0.90, 0.80, 0.85]
]

df = pd.DataFrame(data, columns=['Tramo', 'Escenario', 'Var_TP', 'Var_Peatonal', 'Var_Logistica', 'Var_Flujo'])

def calcular_icv(row):
    if row['Escenario'] == "1. Base":
        return (row['Var_TP'] * 0.40) + (row['Var_Peatonal'] * 0.35) + (row['Var_Logistica'] * 0.15) + (row['Var_Flujo'] * 0.10)
    elif row['Escenario'] == "2. Alternativa 1":
        return (row['Var_TP'] * 0.35) + (row['Var_Peatonal'] * 0.40) + (row['Var_Logistica'] * 0.15) + (row['Var_Flujo'] * 0.10)
    elif row['Escenario'] == "3. Alternativa 2":
        return (row['Var_TP'] * 0.45) + (row['Var_Peatonal'] * 0.35) + (row['Var_Logistica'] * 0.15) + (row['Var_Flujo'] * 0.05)
    return 0

df['ICV'] = df.apply(calcular_icv, axis=1)

pivot_df = df.pivot(index='Tramo', columns='Escenario', values='ICV')
pivot_df = pivot_df.reindex(tramos)

print("="*65)
print("TABLA PIVOTE: ICV POR TRAMO Y ESCENARIO")
print("="*65)
print(pivot_df.round(3))
print("="*65)

plt.style.use('dark_background')
fig, ax = plt.subplots(figsize=(14, 7))

x = np.arange(len(tramos))
width = 0.25

base_vals = pivot_df["1. Base"].values
alt1_vals = pivot_df["2. Alternativa 1"].values
alt2_vals = pivot_df["3. Alternativa 2"].values

rects1 = ax.bar(x - width, base_vals, width, label="1. Base", color='#d62728')
rects2 = ax.bar(x, alt1_vals, width, label="2. Alternativa 1", color='#ff7f0e')
rects3 = ax.bar(x + width, alt2_vals, width, label="3. Alternativa 2", color='#2ca02c')

ax.axhline(y=0.40, color='red', linestyle='--', linewidth=1.5, label='Límite Crítico')
ax.axhline(y=0.70, color='green', linestyle='--', linewidth=1.5, label='Estándar Óptimo')

ax.set_title("Evolución Espacial del ICV: Análisis Comparativo de la Red", fontsize=16, fontweight='bold', pad=20)
ax.set_ylabel("Índice de Calidad Vial (ICV)", fontsize=12, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(tramos, fontsize=10, fontweight='bold')
ax.set_ylim(0, 1.1)

ax.legend(loc='upper left', bbox_to_anchor=(1, 1), frameon=False)

def agregar_etiquetas(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 5),
                    textcoords="offset points",
                    ha='center', va='bottom', color='white', fontweight='bold', fontsize=10)

agregar_etiquetas(rects1)
agregar_etiquetas(rects2)
agregar_etiquetas(rects3)

plt.savefig('versus_5_tramos_icv.png', dpi=300, bbox_inches='tight')
plt.show()

import plotly.graph_objects as go

font_family = "Helvetica, Arial, sans-serif"
header_bg_color = '#1b3a4b'
header_font_color = 'white'
cell_bg_white = '#ffffff'
cell_bg_light = '#f8f9fa'

color_rojo_inviable = '#ffcccc'
color_amarillo_cero = '#fff2cc'

row_colors_t1 = [cell_bg_white, cell_bg_light, color_rojo_inviable]

fig1 = go.Figure(data=[go.Table(
    header=dict(
        values=['<b>Escenario de Inversión (San Miguel)</b>', '<b>Monto Estimado (CLP)</b>', '<b>Cobertura</b>'],
        fill_color=header_bg_color,
        font=dict(color=header_font_color, size=14, family=font_family),
        align='center',
        height=40
    ),
    cells=dict(
        values=[
            ['Costo Total Red Vial (Reparar todo)', 'Presupuesto Disponible FNDR', '<b>Déficit de Inversión</b>'],
            ['$ 11.610.000.000', '$ 2.500.000.000', '<b>-$ 9.110.000.000</b>'],
            ['100%', '21.5%', '<b>Inviable</b>']
        ],
        fill_color=[row_colors_t1] * 3,
        font=dict(color='#212529', size=13, family=font_family),
        align=['left', 'center', 'center'],
        height=35
    )
)])

fig1.update_layout(
    title=dict(text="<b>Tabla 1: El Escenario Macro (Filtro del Algoritmo)</b>", font=dict(size=18, family=font_family)),
    margin=dict(l=20, r=20, t=60, b=20),
    height=220
)

row_colors_t2 = [cell_bg_white, cell_bg_light, cell_bg_white, color_amarillo_cero]

fig2 = go.Figure(data=[go.Table(
    header=dict(
        values=['<b>Ítem de Obras Civiles (Estándar MOP/MINVU)</b>', '<b>Valor Unitario (CLP)</b>'],
        fill_color=header_bg_color,
        font=dict(color=header_font_color, size=14, family=font_family),
        align='center',
        height=40
    ),
    cells=dict(
        values=[
            [' Repavimentación (Carpeta Asfáltica)',
             ' Señalización (Horizontal y Vertical)',
             ' Iluminación LED (Seguridad)',
             '<b> Expropiaciones / Compra de Terrenos</b>'],
            ['$ 8.500 / m²',
             '$ 1.200 / m²',
             '$ 3.500 / m lineal',
             '<b>$ 0 (CERO)</b>']
        ],
        fill_color=[row_colors_t2] * 2,
        font=dict(color='#212529', size=13, family=font_family),
        align=['left', 'center'],
        height=35
    )
)])

fig2.update_layout(
    title=dict(text="<b>Tabla 2: Costos de Nuestra Intervención (La Solución)</b>", font=dict(size=18, family=font_family)),
    margin=dict(l=20, r=20, t=60, b=20),
    height=250
)

fig1.show()
fig2.show()

import plotly.graph_objects as go

LARGO_TRAMO_M = 500
ANCHO_CALZADA_M = 12.1
AREA_PROYECTO_M2 = LARGO_TRAMO_M * ANCHO_CALZADA_M

COSTOS_UNITARIOS = {
    'repavimentacion': 76_500,
    'ciclovía':       12_000,
    'señalización':    1_200,
    'iluminación':     3_500,
}

COSTO_DEMOLICION_FIJO = 10_000_000
COSTO_EXPROPIACIONES  = 0

TASA_SOCIAL        = 0.06
HORIZONTE_ANOS     = 20
VALOR_TIEMPO_UF_H  = 0.005
COSTO_ACC_CLP      = 50_000_000
REDUCCION_ACC      = 0.25

inversion_inicial = 274_420_700
beneficio_anual   = 64_650_000

factor_anualidad = (1 - (1 + TASA_SOCIAL)**-HORIZONTE_ANOS) / TASA_SOCIAL
vab = beneficio_anual * factor_anualidad

van_social = vab - inversion_inicial
ratio_bc = vab / inversion_inicial
payback = inversion_inicial / beneficio_anual

tir_social = 0.0
for r in range(1, 10000):
    tasa_prueba = r / 10000
    npv_prueba = beneficio_anual * ((1 - (1 + tasa_prueba)**-HORIZONTE_ANOS) / tasa_prueba) - inversion_inicial
    if npv_prueba < 0:
        tir_social = tasa_prueba - 0.0001
        break

def fmt_clp(val): return f"${val:,.0f}".replace(",", ".")
def fmt_pct(val): return f"{val*100:.2f}%".replace(".", ",")
def fmt_dec(val): return f"{val:.2f}".replace(".", ",")

interpretacion_tir = f"Ampliamente superior al {fmt_pct(TASA_SOCIAL)} exigido." if tir_social > TASA_SOCIAL else "No supera la tasa exigida."

font_family = "Helvetica, Arial, sans-serif"
header_bg_color = 'midnightblue'
header_font_color = 'white'
color_blanco = '#ffffff'
color_gris = '#f8f9fa'
color_amarillo_suave = '#fff2cc'

fig1 = go.Figure(data=[go.Table(
    columnwidth=[150, 400, 200],
    header=dict(
        values=['<b>Período</b>', '<b>Descripción del Ítem</b>', '<b>Monto / Valor</b>'],
        fill_color=header_bg_color,
        font=dict(color=header_font_color, size=14, family=font_family),
        align=['center', 'left', 'center'],
        height=40
    ),
    cells=dict(
        values=[
            ['<b>Año 0</b>', f'Años 1 al {HORIZONTE_ANOS}', 'Parámetro MIDEPLAN', 'Parámetro Proyecto'],
            ['<b>Inversión Inicial (CAPEX) - Sin Expropiación</b>',
             'Beneficio Social Anual (Ahorro tiempo camiones/vehículos, accidentes, integración ciclovías/peatones)',
             'Tasa Social de Descuento (TSD)',
             'Horizonte de Evaluación'],
            [f'<b>-{fmt_clp(inversion_inicial)}</b>', f'+{fmt_clp(beneficio_anual)}', f'{fmt_pct(TASA_SOCIAL)} Anual', f'{HORIZONTE_ANOS} Años']
        ],
        fill_color=[[color_amarillo_suave, color_blanco, color_gris, color_blanco]*3],
        font=dict(color='#212529', size=13, family=font_family),
        align=['center', 'left', 'center'],
        height=35
    )
)])

fig1.update_layout(
    title=dict(text="<b>1. Resumen de Flujo de Caja Social y Parámetros</b>", font=dict(size=18, family=font_family)),
    margin=dict(l=20, r=20, t=50, b=20),
    height=220
)

row_colors_t2 = [color_blanco, color_gris, color_blanco, color_gris]

fig2 = go.Figure(data=[go.Table(
    columnwidth=[200, 200, 150, 250],
    header=dict(
        values=['<b>Indicador Económico</b>', '<b>Metodología de Cálculo</b>', '<b>Resultado Final</b>', '<b>Interpretación Técnica</b>'],
        fill_color=header_bg_color,
        font=dict(color=header_font_color, size=14, family=font_family),
        align=['left', 'center', 'center', 'left'],
        height=40
    ),
    cells=dict(
        values=[
            ['<b>VAN Social</b> (Valor Actual Neto)',
             '<b>TIR Social</b> (Tasa Interna de Retorno)',
             '<b>Ratio B/C</b> (Beneficio/Costo)',
             '<b>Payback Simple</b> (Recuperación)'],
            ['VAB - Inversión Inicial',
             'Tasa que iguala VAN a $0',
             'VAB / Inversión Inicial',
             'Inversión / Beneficio Anual'],
            [f'<b>+{fmt_clp(van_social)}</b>',
             f'<b>{fmt_pct(tir_social)}</b>',
             f'<b>{fmt_dec(ratio_bc)}</b>',
             f'<b>{fmt_dec(payback)} Años</b>'],
            ['Altamente rentable en valor presente.' if van_social > 0 else 'No rentable en valor presente.',
             interpretacion_tir,
             f'Retorna ${fmt_dec(ratio_bc)} por cada $1 invertido.',
             f'Se recupera en aprox. {int(payback)} años y {int((payback-int(payback))*12)} meses.']
        ],
        fill_color=[row_colors_t2]*4,
        font=dict(color='#212529', size=13, family=font_family),
        align=['left', 'center', 'center', 'left'],
        height=40
    )
)])

fig2.update_layout(
    title=dict(text="<b>2. Resultados de Evaluación Económica MIDEPLAN</b>", font=dict(size=18, family=font_family)),
    margin=dict(l=20, r=20, t=50, b=20),
    height=250
)

fig1.show()
fig2.show()

print("\n" + "="*110)
print(" 1. RESUMEN DE FLUJO DE CAJA SOCIAL Y PARÁMETROS")
print("="*110)
print(f" {'Período / Tipo':<22} | {'Descripción del Ítem':<68} | {'Monto / Valor':<15}")
print("-"*110)
print(f" {'Año 0':<22} | {'Inversión Inicial (CAPEX) - Sin Expropiación':<68} | {'-'+fmt_clp(inversion_inicial):<15}")
print(f" {f'Años 1 al {HORIZONTE_ANOS}':<22} | {'Beneficio Social Anual (Ahorro tiempo, accidentes, CO2)':<68} | {'+'+fmt_clp(beneficio_anual):<15}")
print(f" {'Parámetro MIDEPLAN':<22} | {'Tasa Social de Descuento (TSD)':<68} | {fmt_pct(TASA_SOCIAL)+' Anual':<15}")
print(f" {'Parámetro Proyecto':<22} | {'Horizonte de Evaluación':<68} | {f'{HORIZONTE_ANOS} Años':<15}")
print("="*110)

print("\n" + "="*125)
print(" 2. RESULTADOS DE EVALUACIÓN ECONÓMICA (SISTEMA NACIONAL DE INVERSIONES)")
print("="*125)
print(f" {'Indicador Económico':<38} | {'Metodología de Cálculo':<26} | {'Resultado':<15} | {'Interpretación Técnica':<38}")
print("-"*125)
print(f" {'VAN Social (Valor Actual Neto)':<38} | {'VAB - Inversión Inicial':<26} | {'+'+fmt_clp(van_social):<15} | {'Altamente rentable en valor presente.' if van_social > 0 else 'No rentable.':<38}")
print(f" {'TIR Social (Tasa Interna de Retorno)':<38} | {'Tasa que iguala VAN a $0':<26} | {fmt_pct(tir_social):<15} | {interpretacion_tir:<38}")
print(f" {'Ratio B/C (Beneficio/Costo)':<38} | {'VAB / Inversión Inicial':<26} | {fmt_dec(ratio_bc):<15} | {f'Retorna ${fmt_dec(ratio_bc)} por cada $1 invertido.':<38}")
print(f" {'Payback Simple (Recuperación)':<38} | {'Inversión / Beneficio':<26} | {f'{fmt_dec(payback)} Años':<15} | {f'Se recupera en aprox. {int(payback)} años y {int((payback-int(payback))*12)} meses.':<38}")
print("="*125 + "\n")

import matplotlib.pyplot as plt
from google.colab import files

plt.style.use('dark_background')

categorias = ['Transporte Público', 'Seguridad Peatonal', 'Logística', 'Flujo Vehicular']
colores = ['#3182bd', '#41b6c4', '#fd8d3c', '#e6550d']

pesos_actual = [40, 35, 15, 10]
pesos_alt1 = [35, 40, 15, 10]
pesos_alt2 = [45, 35, 15, 5]

datos = [pesos_actual, pesos_alt1, pesos_alt2]
titulos = ["Escenario 1\n(Situación Actual)", "Escenario 2\n(Alternativa 1: Peatonal)", "Escenario 3\n(Alternativa 2: Microhub)"]

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.suptitle("Evolución de Pesos Dinámicos: Evaluación Multicriterio del ICV", fontsize=18, fontweight='bold', y=1.05)

for i, ax in enumerate(axes):
    wedges, texts, autotexts = ax.pie(
        datos[i],
        colors=colores,
        autopct='%1.0f%%',
        startangle=90,
        pctdistance=0.75,
        wedgeprops=dict(width=0.4, edgecolor='#121212', linewidth=2)
    )
    plt.setp(autotexts, size=12, weight="bold", color="white")
    ax.set_title(titulos[i], fontsize=14, fontweight='bold', pad=15)

fig.legend(wedges, categorias, loc='lower center', ncol=4, bbox_to_anchor=(0.5, -0.1), fontsize=12, frameon=False)

plt.tight_layout()
ruta_salida = 'distribucion_pesos_dinamicos.png'
plt.savefig(ruta_salida, dpi=300, bbox_inches='tight')
plt.show()

files.download(ruta_salida)

import plotly.graph_objects as go
import pandas as pd

emision_base_co2 = 254.8
emision_alt2_co2 = 186.2

reduccion_abs = emision_base_co2 - emision_alt2_co2
pct_reduccion_co2 = (reduccion_abs / emision_base_co2) * 100

criterios_clean = [
    'Longitud de Cola (Disipación de ondas)',
    'Velocidad de Operación (Erradicación stop-and-go)',
    'Demora Promedio (Confiabilidad)',
    'Emisiones de CO2 (Mitigación Ambiental)'
]

base_clean = [
    '78 metros (Media sostenida, alta volatilidad)',
    '21 km/h (Flujo inestable)',
    '1.58 min/veh. (Picos de alta demora)',
    f'{emision_base_co2} g/veh-km (Altas por aceleración/frenado)'
]

alt2_clean = [
    '52 metros (-33.3%) (Comprime varianza geométrica)',
    '28 km/h (+33.3%) (Velocidad de crucero estable)',
    '1.20 min/veh. (-24.1%) (Mayor predictibilidad)',
    f'{emision_alt2_co2} g/veh-km (-{pct_reduccion_co2:.2f}%) (Flujo estabilizado)'
]

font_family = "Helvetica, Arial, sans-serif"

encabezados = [
    '<b>Indicador Operativo / Evaluación</b>',
    '<b>Escenario Base:<br>Situación Actual</b>',
    '<b>Alternativa 2:<br>Microhub Logístico (ELEGIDA)</b>'
]

criterios = [
    '<b>Longitud de Cola</b><br>(Disipación de ondas de choque)',
    '<b>Velocidad de Operación</b><br>(Erradicación del stop-and-go)',
    '<b>Demora Promedio</b><br>(Confiabilidad en la red)',
    '<b>Emisiones de CO2</b><br>(Mitigación ambiental)'
]

base_html = [
    '<b>78 metros</b><br>Media sostenida por saturación recurrentes.',
    '<b>21 km/h</b><br>Flujo inestable marcado por detenciones continuas.',
    '<b>1.58 min/veh</b><br>Baja predictibilidad en tiempos de viaje.',
    f'<b>{emision_base_co2} g/veh-km</b><br>Derivadas de constantes ciclos de aceleración.'
]

alt2_html = [
    '<b>52 metros (-33%)</b><br>Mitiga propagación hacia atrás.',
    '<b>28 km/h</b><br>Absorbe detenciones, alcanzando crucero estable.',
    '<b>1.20 min/veh</b><br>Estrecha banda de fluctuación.',
    f'<b>{emision_alt2_co2} g/veh-km (-{pct_reduccion_co2:.2f}%)</b><br>Reducción por flujo mixto continuo.'
]

fig = go.Figure(data=[go.Table(
    columnwidth=[220, 260, 260],
    header=dict(
        values=encabezados,
        line_color='darkslategray',
        fill_color=['midnightblue', '#721c24', '#155724'],
        align='center',
        font=dict(color='white', size=14, family=font_family),
        height=55
    ),
    cells=dict(
        values=[criterios, base_html, alt2_html],
        line_color='darkslategray',
        fill_color=['#f8f9fa', '#f8d7da', '#d4edda'],
        align=['left', 'center', 'center'],
        font=dict(color='#212529', size=13, family=font_family),
        height=65
    )
)])

fig.update_layout(
    title_text="<b>Tabla de Resultados: Microsimulación SUMO (Base vs. Microhub)</b>",
    title_x=0.5,
    margin=dict(l=20, r=20, t=60, b=20),
    height=400
)

fig.show()

df_evaluacion = pd.DataFrame({
    'Indicador Operativo / Evaluación': criterios_clean,
    'Escenario Base': base_clean,
    'Alternativa 2 (Microhub)': alt2_clean
})

print("\n" + "="*110)
print(" MINI TABLA DE EVALUACIÓN COMPARATIVA (RESULTADOS SUMO)")
print("="*110)
print(df_evaluacion.to_string(index=False))
print("="*110 + "\n")

print(" REPORTE DE CÁLCULO DE EMISIONES Y CO-BENEFICIOS AMBIENTALES")
print("-" * 110)
print(f" Cálculo exacto: (({emision_base_co2} - {emision_alt2_co2}) / {emision_base_co2}) * 100 = {pct_reduccion_co2:.2f}% de reducción de CO2.")
print("\n ¿Qué consideraciones se tomaron para este cálculo en la microsimulación?")
print(" 1. Erradicación del 'Stop-and-Go': En el escenario base (21 km/h), los vehículos frenan a 0")
print("    y vuelven a acelerar constantemente. Las aceleraciones desde inercia cero exigen el máximo")
print("    esfuerzo del motor, multiplicando las emisiones. La Alternativa 2 estabiliza la velocidad (28 km/h).")
print(" 2. Reducción de tiempo en ralentí (Idling): La demora promedio bajó de 1.58 a 1.20 min/veh (-24%).")
print("    Menos tiempo de espera en la congestión significa menos combustible quemado con el vehículo detenido.")
print(" 3. Efecto de Disipación de Colas: Al reducir la cola de 78m a 52m, se disminuye la cantidad de")
print("    vehículos estancados en un mismo tramo geométrico emitiendo gases simultáneamente.")
print("="*110 + "\n")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.patches as mpatches

data = {
    "Sub-tramo": [
        "Tramo 1 (Fernando Lazcano)",
        "Tramo 2 (Bloqueos Comerciales)",
        "Tramo 3 (Intermedio A)",
        "Tramo 4 (Intermedio B)",
        "Tramo 5 (Curiñanca)"
    ],
    "var_tp": [0.85, 0.15, 0.65, 0.80, 0.90],
    "var_peatonal": [0.70, 0.35, 0.60, 0.75, 0.85],
    "var_logistica": [0.60, 0.40, 0.55, 0.65, 0.70],
    "var_flujo": [0.50, 0.25, 0.60, 0.70, 0.80]
}

df_icv = pd.DataFrame(data)

W_TP = 0.40
W_PEATONAL = 0.35
W_LOGISTICA = 0.15
W_FLUJO = 0.10

df_icv["ICV_Final"] = (
    (df_icv["var_tp"] * W_TP) +
    (df_icv["var_peatonal"] * W_PEATONAL) +
    (df_icv["var_logistica"] * W_LOGISTICA) +
    (df_icv["var_flujo"] * W_FLUJO)
)

def clasificar_icv(valor):
    if valor > 0.7:
        return "Óptimo"
    elif 0.4 < valor <= 0.7:
        return "Saturado"
    else:
        return "Crítico"

df_icv["Diagnóstico"] = df_icv["ICV_Final"].apply(clasificar_icv)

print("\n" + "="*65)
print(" RESULTADOS ICV: ESCENARIO PRIORIDAD TRANSPORTE PÚBLICO")
print(" SENTIDO: Fernando Lazcano -> Curiñanca")
print("="*65)
print(df_icv.to_string(index=False, float_format="{:.3f}".format))
print("="*65 + "\n")

plt.style.use('dark_background')
fig, ax = plt.subplots(figsize=(10, 6))

colores_diagnostico = {
    "Óptimo": "#2ca02c",
    "Saturado": "#ff7f0e",
    "Crítico": "#d62728"
}

bar_colors = df_icv["Diagnóstico"].map(colores_diagnostico)

bars = ax.barh(df_icv["Sub-tramo"], df_icv["ICV_Final"], color=bar_colors, edgecolor='white', linewidth=0.5)

ax.set_xlim(0, 1)
ax.set_xlabel("Valor del Índice de Calidad Vial (ICV)", fontsize=12, fontweight='bold', labelpad=10)
ax.set_title("ICV por Sub-tramo en Gran Avenida\n(Fernando Lazcano -> Curiñanca)", fontsize=14, fontweight='bold', pad=15)

ax.invert_yaxis()

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

for bar in bars:
    ancho = bar.get_width()
    ax.text(ancho + 0.02,
            bar.get_y() + bar.get_height()/2,
            f'{ancho:.2f}',
            va='center',
            ha='left',
            color='white',
            fontweight='bold',
            fontsize=11)

leyenda_patches = [mpatches.Patch(color=color, label=label) for label, color in colores_diagnostico.items()]
ax.legend(handles=leyenda_patches, loc='lower right', title="Categoría", frameon=False)

plt.tight_layout()
archivo_salida = 'icv_tp_fernando_lazcano_curinanca.png'
plt.savefig(archivo_salida, dpi=300, transparent=False)
print(f"Grafico exportado exitosamente como: {archivo_salida}")

plt.show()

import matplotlib.pyplot as plt

pesos = [40, 35, 15, 10]
etiquetas = [
    'Transporte Público',
    'Seguridad Peatonal',
    'Eficiencia Logística',
    'Flujo Vehicular'
]

plt.style.use('dark_background')
colores = ['#4A90E2', '#50E3C2', '#F5A623', '#D0021B']

explode = (0.1, 0, 0, 0)

fig, ax = plt.subplots(figsize=(8, 8))

wedges, texts, autotexts = ax.pie(
    pesos,
    explode=explode,
    labels=etiquetas,
    colors=colores,
    autopct='%1.0f%%',
    shadow=True,
    startangle=140,
    textprops=dict(color="w", fontsize=12, fontweight='bold'),
    wedgeprops=dict(edgecolor='w', linewidth=1.5)
)

plt.setp(autotexts, size=14, weight="bold", color='white')

ax.set_title(
    "Distribución de Criterios: Índice de Calidad Vial (ICV)\nEscenario de Prioridad al Transporte Público",
    fontsize=14,
    fontweight='bold',
    pad=20
)

plt.tight_layout()

archivo_salida = 'distribucion_pesos_icv.png'
plt.savefig(archivo_salida, dpi=300, transparent=False)
print(f"Grafico pastel exportado exitosamente como: {archivo_salida}")

plt.show()