# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_TGVRTHeuCb7bNt1wdjZogzwZ6NzX8h
"""



#pip install osmnx geopandas folium networkx scikit-learn seaborn
#pip install osmnx geopandas

import sys
import warnings
import os
warnings.filterwarnings('ignore')

import osmnx as ox
import networkx as nx
import geopandas as gpd
import pandas as pd
import numpy as np


OUTPUT_FOLDER = 'PROYECTO_QGIS_SAN_MIGUEL'
if not os.path.exists(OUTPUT_FOLDER):
    os.makedirs(OUTPUT_FOLDER)

ox.settings.log_console = False
ox.settings.use_cache = True

PLACE = 'San Miguel, Región Metropolitana, Chile'


PRESUPUESTO_CLP = 1_937_670_000
ANCHO_PROMEDIO_M = 7.0
COSTOS_UNITARIOS = {
    'repavimentacion': 21194,
    'ciclovía': 12000,
    'señalización': 1200,
    'iluminación': 3500,
}

print(f"--- Iniciando Procesamiento Integrado para {PLACE} ---")


print("Generando Red Vial y Análisis Económico...")
G = ox.graph_from_place(PLACE, network_type='all')
G_simple = nx.DiGraph(G)


betweenness = nx.betweenness_centrality(G_simple, weight='length', normalized=True)
degree = dict(G.degree())

edges = ox.graph_to_gdfs(G, nodes=False).reset_index()


edges['betweenness'] = edges.apply(lambda r: (betweenness.get(r['u'], 0) + betweenness.get(r['v'], 0)) / 2, axis=1)
edges['conectividad_nodos'] = edges.apply(lambda r: (degree.get(r['u'], 0) + degree.get(r['v'], 0)) / 2, axis=1)
edges['length_m'] = edges['length'].astype(float)


edges['costo_pavimento'] = edges['length_m'] * ANCHO_PROMEDIO_M * COSTOS_UNITARIOS['repavimentacion']
edges['costo_señaletica'] = edges['length_m'] * COSTOS_UNITARIOS['señalización']
edges['costo_total_tramo'] = edges['costo_pavimento'] + edges['costo_señaletica']


edges['geometry_wkt'] = edges['geometry'].apply(lambda x: x.wkt)


edges.to_file(os.path.join(OUTPUT_FOLDER, "01_RED_VIAL_ANALISIS.geojson"), driver='GeoJSON')


filtros_avanzados = {
    "02_Salud_y_Emergencia": {"amenity": ["hospital", "clinic", "pharmacy", "fire_station"]},
    "03_Educacion": {"amenity": ["school", "university", "kindergarten"]},
    "04_Transporte_y_Metro": {"public_transport": ["stop_position", "platform"], "railway": "subway_entrance", "highway": "bus_stop"},
    "05_Comercio_y_Servicios": {"amenity": ["bank", "marketplace", "supermarket"], "shop": ["supermarket", "mall"]},
    "06_Zonas_Peatonales": {"highway": ["crossing", "pedestrian", "footway"]},
    "07_Areas_Verdes": {"leisure": ["park", "playground"], "landuse": "grass"}
}

for nombre, tags in filtros_avanzados.items():
    try:
        print(f"Generando capa: {nombre}...")
        gdf = ox.features_from_place(PLACE, tags=tags)
        if not gdf.empty:

            gdf = gdf.loc[:, ~gdf.columns.duplicated()]
            for col in gdf.columns:
                if gdf[col].apply(lambda x: isinstance(x, (list, dict))).any():
                    gdf[col] = gdf[col].astype(str)

            #
            gdf.to_file(os.path.join(OUTPUT_FOLDER, f"{nombre}.geojson"), driver='GeoJSON')
    except:
        print(f"⚠ No se encontraron datos suficientes para {nombre}")


csv_path = os.path.join(OUTPUT_FOLDER, "TABLA_MAESTRA_PRIORIZACION.csv")
pd.DataFrame(edges.drop(columns='geometry')).to_csv(csv_path, index=False)

print(f"\n✔ PROCESO FINALIZADO.")
print(f"Archivos disponibles en la carpeta '{OUTPUT_FOLDER}' del menú lateral.")